output_prefix: dirichlet_S2

defaults:
  n_runs: 10
  n_client: 10
  k_client: 15
  k_server: 15
  partition: 1 #random, positive float
  aggregation: kmeans #kmeans, kmedian, trimmed_kmeans, mean_shift_filtering
  weighting : False # False, count, ess, precision
  verbose: False
  r: 2
  snr_db: 30
  eps : 0
  scheme : dense # rep, dense
  solver : ols # ols, lts, huber
  alpha : 0.2


experiments:
  - name: No weighting
    r: 1
    weighting : False
  - name: Count weighting
    r: 1
    weighting : count
  # - name: kmeans r=4 ess
  #   aggregation: kmeans
  #   r: 1
  #   weighting : "ess"
  # - name: ols
  #   aggregation: weighted_kmeans
  #   solver : ols
  # - name: lts
  #   aggregation: weighted_kmeans
  #   solver : lts
  # - name: dirichlet
  #   partition: dirichlet
  #   partition: 1
  # - name: random
  #   partition: random
  # - name: random_weighted
  #   partition: random
  #   aggregation: weighted_kmeans
  # - name: Centralized
  #   n_client: 0

