output_prefix: letter

defaults:
  n_runs: 5
  n_client: 50
  k_client: 26
  k_server: 26
  param_r: 1
  snr_db: 10
  flip_prob: 0.01
  partition: random
  noise: gaussian
  aggregation: kmeans
  verbose: false

experiments:
  - name: Kmeans r=1
    param_r: 1
    aggregation: kmeans

  - name: Kmeans r=4
    param_r: 4
    aggregation: kmeans

  - name: Centralized
    n_client: 0

